name: Generate Automation 
on: push
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      - name: Install Dep
        run: |
          python -m pip install --upgrade pip 
          pip install pyyaml
      - name: Runner
        run: |
          python feed.py
      - name: Push Repo
        run:
          git add .
          git commit -m 'automated'
          git push
